import prgm
from tkinter import Toplevel

def main(_diag=False):
    root=Toplevel()
    prgm.Label(root,text='A et B représentent des nombres\ndifférents compris entre 2 et 12').grid(column=0,row=0,columnspan=2)
    prgm.Label(root,text='',width=30).grid(column=0,row=1,columnspan=2)
    prgm.Label(root,text='Combinaison',font=('TkDefaultFont',10,'bold')).grid(column=0,row=2)
    prgm.Label(root,text='Points',font=('TkDefaultFont',10,'bold')).grid(column=1,row=2)
    prgm.Label(root,text='A – A').grid(column=0,row=3)
    prgm.Label(root,text='1').grid(column=1,row=3)
    prgm.Label(root,text='A – A – A').grid(column=0,row=4)
    prgm.Label(root,text='3').grid(column=1,row=4)
    prgm.Label(root,text='A – A – A – A').grid(column=0,row=5)
    prgm.Label(root,text='6').grid(column=1,row=5)
    prgm.Label(root,text='A – A – A – A – A').grid(column=0,row=6)
    prgm.Label(root,text='10').grid(column=1,row=6)
    prgm.Label(root,text='A – A – B – B').grid(column=0,row=7)
    prgm.Label(root,text='3').grid(column=1,row=7)
    prgm.Label(root,text='A – A – A – B – B').grid(column=0,row=8)
    prgm.Label(root,text='8').grid(column=1,row=8)
    prgm.Label(root,text='A – A+1 – A+2 – A+3 – A+4').grid(column=0,row=9)
    prgm.Label(root,text='8').grid(column=1,row=9)
    prgm.Label(root,text='2 – 3 – 4 – 5 – 6').grid(column=0,row=10)
    prgm.Label(root,text='12').grid(column=1,row=10)
    prgm.Label(root,text='8 – 9 – 10 – 11 – 12').grid(column=0,row=11)
    prgm.Label(root,text='12').grid(column=1,row=11)
    prgm.Label(root,text='Diagonales').grid(column=0,row=12)
    prgm.Label(root,text='×2').grid(column=1,row=12)
    prgm.Label(root,text='',width=30).grid(column=0,row=13,columnspan=2)
    bouton_fermer=prgm.Button(root,text='Fermer',command=root.destroy)
    bouton_fermer.grid(column=0,row=14,columnspan=2)
    root.title('Liste des combinaisons')
    root.resizable(width=False,height=False)
    if prgm.name=='nt':
        root.tk.call('wm','iconphoto',root._w,prgm.img)
    prgm.root.wait_window(root)