from tkinter import *
import matplotlib.pyplot as plt
import numpy as np
from math import *
import entier
import fraction
import quitter

Fen=Tk()

Label(Fen,text='Coefficients entiers').grid(column=0,row=0,columnspan=2)
Label(Fen,text='a=').grid(column=0,row=1,sticky='e')
Label(Fen,text='b=').grid(column=0,row=3,sticky='e')
Label(Fen,text='c=').grid(column=0,row=5,sticky='e')
ValeurA=IntVar(Fen)
ValeurB=IntVar(Fen)
ValeurC=IntVar(Fen)
ValA=Spinbox(Fen,textvariable=ValeurA,from_=-inf,to=inf,increment=1,width=10)
ValA.grid(column=1,row=1)
ValB=Spinbox(Fen,textvariable=ValeurB,from_=-inf,to=inf,increment=1,width=10)
ValB.grid(column=1,row=3)
ValC=Spinbox(Fen,textvariable=ValeurC,from_=-inf,to=inf,increment=1,width=10)
ValC.grid(column=1,row=5)
BoutonCalc=Button(Fen,text="Calculer",command=entier.main_ent)
BoutonCalc.grid(column=0,row=7,columnspan=2)

Label(Fen,text='Coefficients décimaux').grid(column=3,row=0,columnspan=2)
Label(Fen,text='Num\u00E9rateur de a=').grid(column=3,row=1,sticky='e')
Label(Fen,text='D\u00E9nominateur de a=').grid(column=3,row=2,sticky='e')
Label(Fen,text='Num\u00E9rateur de b=').grid(column=3,row=3,sticky='e')
Label(Fen,text='D\u00E9nominateur de b=').grid(column=3,row=4,sticky='e')
Label(Fen,text='Num\u00E9rateur de c=').grid(column=3,row=5,sticky='e')
Label(Fen,text='D\u00E9nominateur de c=').grid(column=3,row=6,sticky='e')
ValeurA_n=IntVar(Fen)
ValeurA_d=IntVar(Fen)
ValeurB_n=IntVar(Fen)
ValeurB_d=IntVar(Fen)
ValeurC_n=IntVar(Fen)
ValeurC_d=IntVar(Fen)
ValA_n=Spinbox(Fen,textvariable=ValeurA_n,from_=-inf,to=inf,increment=1,width=10)
ValA_n.grid(column=4,row=1)
ValA_d=Spinbox(Fen,textvariable=ValeurA_d,from_=1,to=inf,increment=1,width=10)
ValA_d.grid(column=4,row=2)
ValB_n=Spinbox(Fen,textvariable=ValeurB_n,from_=-inf,to=inf,increment=1,width=10)
ValB_n.grid(column=4,row=3)
ValB_d=Spinbox(Fen,textvariable=ValeurB_d,from_=1,to=inf,increment=1,width=10)
ValB_d.grid(column=4,row=4)
ValC_n=Spinbox(Fen,textvariable=ValeurC_n,from_=-inf,to=inf,increment=1,width=10)
ValC_n.grid(column=4,row=5)
ValC_d=Spinbox(Fen,textvariable=ValeurC_d,from_=1,to=inf,increment=1,width=10)
ValC_d.grid(column=4,row=6)
BoutonCalc=Button(Fen,text="Calculer",command=fraction.main_frac)
BoutonCalc.grid(column=3,row=7,columnspan=2)

BoutonQuit=Button(Fen,text="Quitter",command=quitter.main_quit)
BoutonQuit.grid(column=7,row=10)

Col3_Row1=Label(Fen,width=5)
Col3_Row1.grid(column=2,row=0)
Col3_Row2=Label(Fen,width=5)
Col3_Row2.grid(column=2,row=1)
Col3_Row3=Label(Fen,width=5)
Col3_Row3.grid(column=2,row=2)
Col3_Row4=Label(Fen,width=5)
Col3_Row4.grid(column=2,row=3)
Col3_Row5=Label(Fen,width=5)
Col3_Row5.grid(column=2,row=4)
Col3_Row6=Label(Fen,width=5)
Col3_Row6.grid(column=2,row=5)
Col3_Row7=Label(Fen,width=5)
Col3_Row7.grid(column=2,row=6)
Col3_Row8=Label(Fen,width=5)
Col3_Row8.grid(column=2,row=7)
Col3_Row9=Label(Fen,width=5)
Col3_Row9.grid(column=2,row=8)
Col3_Row10=Label(Fen,width=5)
Col3_Row10.grid(column=2,row=9)
Col3_Row11=Label(Fen,width=5)
Col3_Row11.grid(column=2,row=10)

Col6_Row1=Label(Fen,width=5)
Col6_Row1.grid(column=5,row=0)
Col6_Row2=Label(Fen,width=5)
Col6_Row2.grid(column=5,row=1)
Col6_Row3=Label(Fen,width=5)
Col6_Row3.grid(column=5,row=5)
Col6_Row4=Label(Fen,width=5)
Col6_Row4.grid(column=5,row=3)
Col6_Row5=Label(Fen,width=5)
Col6_Row5.grid(column=5,row=4)
Col6_Row6=Label(Fen,width=5)
Col6_Row6.grid(column=5,row=5)
Col6_Row7=Label(Fen,width=5)
Col6_Row7.grid(column=5,row=6)
Col6_Row8=Label(Fen,width=5)
Col6_Row8.grid(column=5,row=7)
Col6_Row9=Label(Fen,width=5)
Col6_Row9.grid(column=5,row=8)
Col6_Row10=Label(Fen,width=5)
Col6_Row10.grid(column=5,row=9)
Col6_Row11=Label(Fen,width=5)
Col6_Row11.grid(column=5,row=10)

Col7=Label(Fen,width=100)
Col7.grid(column=6,row=5)

Fen.title("R\u00E9solution des \u00E9quations du second degr\u00E9 par Th\u00E9o")
Fen.resizable(width=False,height=False)
Fen.mainloop()
